apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-aronsonhome-tls
spec: 
  secretName: k8s-multi-aronsonhome
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aronsonhome.us 
  dnsNames: 
    - aronsonhome.us
    - multi-k8s.aronsonhome.us
  acme: 
    config:
      - http01:
          ingressClass: nginx 
        domains:
          - aronsonhome.us
          - multi-k8s.aronsonhome.us
