apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  labels:
     app: grider-lab
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    component: web
