apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: grider-lab
    tier: client
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      component: web