apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  labels:
     app: grider-lab
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    component: postgres
