apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  labels:
     app: grider-lab
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    component: server
