apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: grider-lab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
  selector:
    matchLabels:
      component: worker